<a href="https://colab.research.google.com/github/nathan2412151-design/numpy_avanzado/blob/main/2_ejercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [ ]:
import numpy as np

In [ ]:
# ejercicio 1
import numpy as np

a = np.array([1, 2, 3, 4])

resultado = np.all(a != 0)
print(resultado)


True


In [ ]:
a = np.array([0, 0, 2, 0])
resultado = np.any(a != 0)
print(resultado)


True


In [ ]:
a = np.array([1, 2, np.nan, np.inf])

tiene_nan = np.any(np.isnan(a))
tiene_inf = np.any(np.isinf(a))

print("¿Tiene NaN?", tiene_nan)
print("¿Tiene infinitos?", tiene_inf)


¿Tiene NaN? True
¿Tiene infinitos? True


In [ ]:
a = np.array([1, 2, np.inf])

tiene_inf = np.any(np.isinf(a))

print(tiene_inf)


True


In [ ]:
# ejercicio 5
a = np.array([1, np.nan, 3])

tiene_nan = np.any(np.isnan(a))
print(tiene_nan)


True


In [ ]:
# ejercicio 6
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])

print("a > b:", a > b)
print("a >= b:", a >= b)
print("a < b:", a < b)
print("a <= b:", a <= b)


a > b: [False False  True]
a >= b: [False  True  True]
a < b: [ True False False]
a <= b: [ True  True False]


In [ ]:
# ejercicio 7
a = np.array([1, 7, 13, 105])
print(a.nbytes)


32


In [ ]:
# ejercicio 8
ceros = np.zeros(10)
unos = np.ones(10)
cincos = np.full(10, 5)

print(ceros)
print(unos)
print(cincos)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


In [ ]:
# ejercicio 9
a = np.arange(30, 71)
print(a)


[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
# ejercicio 10
a = np.arange(30, 71)
pares = a[a % 2 == 0]
print(pares)


[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
# ejercicio 11
matriz = np.eye(3)
print(matriz)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# ejercicio 12
numero = np.random.rand()
print(numero)


0.08470682562013976


In [ ]:
# ejercicio 13
a = np.random.randn(15)
print(a)


[ 1.17644859  0.13395497  1.48465293 -0.16993978  2.17907413 -0.01091316
 -1.31686941  0.8661599   0.18199126 -1.54484579  0.57318093  0.27951419
  0.51800795 -0.45053193 -0.53240905]


In [ ]:
# ejercicio 14
a = np.arange(15, 56)
print(a[1:-1])


[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [ ]:
# ejercicio 15
a = np.linspace(5, 50, 10)
print(a)


[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [ ]:
# ejercicio 16
a = np.arange(21)
a[9:16] *= -1
print(a)


[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [ ]:
# ejercicio 17
a = np.array([1, 2, 3])
lista = a.tolist()
print(lista)


[1, 2, 3]


In [ ]:
# ejercicio 18
lista = [1, 2, 3]
a = np.array(lista)
print(a)


[1 2 3]


In [ ]:
# ejercicio 19
m = np.array([[1, 2], [3, 4]])
pares = (m % 2 == 0)
print(pares)


[[False  True]
 [False  True]]


In [ ]:
# ejercicio 20
m = np.array([[1, 2, 3], [4, 5, 6]])
print(m.shape)


(2, 3)
